
version: 2

sources:
  - name: dbt-demo
    schema: dbt_db
    tables: 
      - name: customers

models:
  - name: stg_customers
    description: "Cleaning customers data"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
